# Docker Compose Configuration
# visit https://docs.docker.com/compose/

version: '3.8'
services:
  # app service for your backend
  app:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      # - node_modules:/usr/src/app/node_modules
    environment:
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASS: ${DATABASE_PASS}
    ports:
      - '${APP_PORT}:${APP_PORT}'
    depends_on:
      - database
    command: npm run start:dev
    env_file:
      - .env

  # start the mongodb service as container
  database:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - mongodb:/data/db
    env_file:
      - .env
    environment:
      MONGO_INITDB_DATABASE: ${DATABASE_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASS}
volumes: 
  # node_modules: {}
  mongodb: